services:
  postgres:
    container_name: totvs-db
    image: postgres:16
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -U usr-totvs -D totvs-db"
      interval: "10s"
      timeout: "5s"
      retries: 5

  backend:
    container_name: 'backend'
    restart: on-failure
    image: gabrielguidini/totvs-back:latest
    build:
      context: ./technical-challenge-back
      dockerfile: Dockerfile
    env_file: ./technical-challenge-back/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    ports:
      - '8080:8080'

  frontend:
    container_name: 'frontend'
    image: gabrielguidini/totvs-front:latest
    build:
      context: ./technical-challenge-front
      dockerfile: Dockerfile
    depends_on:
      - backend
      - postgres
    ports:
      - "3000:3000"

volumes:
  db-data: